    version: '2'
    services:
        web:
            container_name: nginx-container
            build:
                context: ./.docker/
                dockerfile: web.docker
            volumes:
                - ./:/var/www
            ports:
                - "8070:80"
            environment:
                - NGINX_HOST=csat.test
                - NGINX_PORT=80
            links:
                - app
        app:
            container_name: app-container
            build:
                context: ./.docker/
                dockerfile: app.docker
            environment:
                - "DB_PORT=3306"
                - "DB_HOST=mysql"
            volumes:
                - ./:/var/www
            links:
                - mysql
        mysql:
            container_name: mysql-container
            image: mysql:5.7
            environment:
                - "MYSQL_ROOT_PASSWORD=secret"
                - "MYSQL_DATABASE=csat"
            ports:
                - "3306:3306"